### ISSUE TITLE
听说会用于 Creator，建议暂缓实现渲染部分

### ISSUE THREAD

**Issue by jareguo** [fairygui/FairyGUI-cocos2dx#1]
Creator 的 H5 渲染层预计在 1.7 - 1.8 能完成重写，到时会有新的 API，最好等重写后再实现渲染部分以免无法升级到最新版。（除非你们基于 Creator 的现有 UI 组件实现，那样就没兼容性问题）
原生平台渲染层重写时间待定。

**Comment by fairygui** [comment]
了解了，谢谢！
