### ISSUE TITLE
进度条显示不正常

### ISSUE THREAD

**Issue by rekcah1986** [fairygui/FairyGUI-cocos2dx#12]
希望得到这样的：
![image](https://user-images.githubusercontent.com/3055444/40545034-e7fd08f2-605c-11e8-8402-148d8ab16892.png)
实际显示是这样的：
![image](https://user-images.githubusercontent.com/3055444/40545070-07a5db16-605d-11e8-9065-980ec14c6666.png)

**Comment by xiaoguzhu** [comment]
请阅读文档。cocos2dx版本不支持图片的填充方法。
