### ISSUE TITLE
循环列表急停

### ISSUE THREAD

**Issue by L911** [fairygui/FairyGUI-cocos2dx#13]
![image](https://user-images.githubusercontent.com/9498229/40573354-02bb30a6-60f3-11e8-872c-aae576e63608.png)
循环列表 
滚动时会瞬间停止，而且每次都停在第二章那张图片上，说明计算位置时出现了bug

**Comment by xiaoguzhu** [comment]
在刚好跨越边界时会出现突然停止的情况。这个边界通常是6倍于列表项目数的大小。
