### ISSUE TITLE
MovieClip设置为摆动播放模式使程序进入死循环

### ISSUE THREAD

**Issue by L911** [fairygui/FairyGUI-cocos2dx#16]
在MovieClip设置为摆动播放模式后，程序就会进入死循环状态，原因是在UIPackage::loadMovieClip
![image](https://user-images.githubusercontent.com/9498229/40980629-7926b9de-690b-11e8-84aa-10dc129dd421.png)
应为i--？

**Comment by xiaoguzhu** [comment]
应该是了，我改改。其实你可以发起PR成为贡献者啊。

**Comment by L911** [comment]
ok，我试试

**Comment by xiaoguzhu** [comment]
已解决
