### ISSUE TITLE
运行example的问题

### ISSUE THREAD

**Issue by Liaoer** [fairygui/FairyGUI-cocos2dx#2]
libfairygui下Classes 的cpp文件是否也要用到Examples下的Classes中？

**Comment by fairygui** [comment]
打开Examples/proj.win32/Example.sln即可。

**Comment by Liaoer** [comment]
那 Mac呢？。。现在只考虑win下？

**Comment by fairygui** [comment]
大哥，你会不会cocos啊。。

**Comment by fairygui** [comment]
Mac你就用proj.ios_mac里的啊

**Comment by Liaoer** [comment]
打开后Example后，加入 cocos2d 文件夹 ,编译后缺少很多文件，libfairygui没加入呢。。

**Comment by Liaoer** [comment]
libfairygui 只有Win32的工程项目，不考虑加上么？

**Comment by fairygui** [comment]
你可以帮忙加上
