### ISSUE TITLE
虚拟list第一个cell没有全部显示出来，编辑器里没问题

### ISSUE THREAD

**Issue by Will-Z666** [fairygui/FairyGUI-cocos2dx#21]
位置向上偏移了，上边框没显示出来，向下能拖出来

<img width="687" alt="83013213-1a18-4248-9ac1-04ea90ede546" src="https://user-images.githubusercontent.com/28749797/42723416-c07d7276-878f-11e8-80c2-be1b5332a470.png">

**Comment by xiaoguzhu** [comment]
检查你的item组件的制作。

**Comment by Will-Z666** [comment]
<img width="839" alt="70b4798c-71c8-4fa3-b316-37c4bd83d59c" src="https://user-images.githubusercontent.com/28749797/42741646-c5499c28-88e6-11e8-975e-542d42471dbd.png">

看了下 好像没问题，没有超出。在编辑器里预览也没问题呀。

**Comment by xiaoguzhu** [comment]
我的demo测试没发现问题。你发一个demo给我测试。

**Comment by Will-Z666** [comment]
[XGame.zip](https://github.com/fairygui/FairyGUI-cocos2dx/files/2200581/XGame.zip)

github 最新代码，lua环境。跑官方demo没问题。

**Comment by xiaoguzhu** [comment]
是背景那个图形边线的绘制问题，已经修正了。
