### ISSUE TITLE
居中对齐显示不正常，缺少break; 

### ISSUE THREAD

**Issue by Will-Z666** [fairygui/FairyGUI-cocos2dx#22]
<img width="672" alt="191ca140-3431-4ae6-856f-dcf6d8615a40" src="https://user-images.githubusercontent.com/28749797/42811067-2050a0d4-89ec-11e8-85a9-fa60332b9a74.png">

119行和128行缺少break; 居中对齐显示不正常。加上就没问题了。

**Comment by xiaoguzhu** [comment]
谢谢，已经改正了。
