### ISSUE TITLE
UI编辑器和cocos引擎中富文本图片的上下居中不起效果

### ISSUE THREAD

**Issue by sherererlock** [fairygui/FairyGUI-cocos2dx#23]
![image](https://user-images.githubusercontent.com/9498229/42931069-45b3528c-8b71-11e8-87ba-d59525ab987c.png)

如图所示，图片在富文本中的上下居中并没有起到效果

**Comment by xiaoguzhu** [comment]
编辑器中的是已知问题。下个版本会修正。cocos中测试正常。

**Comment by L911** [comment]
我用最新的代码跑了例子，但是图片在富文本中的上下居中仍然没有效果，是因为cocos引擎的代码也要替换吗？
