### ISSUE TITLE
Safe base for a port?

### ISSUE THREAD

**Issue by JSandusky** [fairygui/FairyGUI-cocos2dx#26]
Is this a safe base to use for porting over to create a C++ FairyGUI backend for something other than Cocos2d? Urho3D in particular.

**Comment by xiaoguzhu** [comment]
The contents of the display directory are strongly related to the game engine. This part needs to be reprocessed. The correlation between other code and game engine is very small, only a little adjustment is needed.

**Comment by JSandusky** [comment]
Awesome, I'll give it a whirl! (closing since this isn't a real issue)
