### ISSUE TITLE
文本描边颜色不正确

### ISSUE THREAD

**Issue by zeas2** [fairygui/FairyGUI-cocos2dx#29]
文本如果设置成黑色，描边无论设置成什么颜色，都是黑色的效果
而文本若设置成白色，则描边颜色显示正常

**Comment by xiaoguzhu** [comment]
测试demo后没有发现你说的问题。

**Comment by xiaoguzhu** [comment]
抱歉，请你先测试官方的demo，有问题再提上来。

**Comment by zeas2** [comment]
官方demo：
Basics/Demo_Text
修改左下角的控件n11“如何使用UI编辑器”，开启描边设为白色即可重现
截图：
https://pan.baidu.com/s/1MaHivNK805MGW48KItnl6Q
使用github上最新的FairyGUI-cocos2dx代码，编译使用未经修改的cocos2d-x-3.15.1（除CCLabel增加一处virtual以通过编译）

**Comment by xiaoguzhu** [comment]
的确是有这个问题，已修正。
