### ISSUE TITLE
xcode 编译失败

### ISSUE THREAD

**Issue by Liaoer** [fairygui/FairyGUI-cocos2dx#3]
![image](https://user-images.githubusercontent.com/2783394/32423540-90bf1032-c26c-11e7-8e38-19d7861ca75e.png)

**Comment by fairygui** [comment]
解决了

**Comment by Liaoer** [comment]
![image](https://user-images.githubusercontent.com/2783394/32453425-c6e8c246-c2e1-11e7-9ec7-e491a5ef3cbb.png)
又来新的

**Comment by fairygui** [comment]
已解决
