### ISSUE TITLE
输入框没有被上层UI覆盖

### ISSUE THREAD

**Issue by xiyoo0812** [fairygui/FairyGUI-cocos2dx#32]
如题，输入框的输入没有被上层UI覆盖，导致在上层点击图片的时候会把下层的输入框弹出来。

**Comment by xiaoguzhu** [comment]
https://github.com/fairygui/FairyGUI-cocos2dx/commit/7ded2a95539d1edc522ad4bf8f70e29b4ce7f6fb

**Comment by xiyoo0812** [comment]
测试已经修复了
