### ISSUE TITLE
label的get_title问题

### ISSUE THREAD

**Issue by xiyoo0812** [fairygui/FairyGUI-cocos2dx#33]
label的getText，直接返回了_title，使用设置方法调用没有问题，但是如果是输入label手动输入的内容就get不到值。
建议重载getTitle，gettext的时候返回getTitle。
const std::string& GLabel::getTitle() const
{
	if (_titleObject != nullptr)
		return _titleObject->getText();
	return _title;
}

**Comment by xiaoguzhu** [comment]
对的。后续会改正。
