### ISSUE TITLE
用“自定义遮罩”对图片进行裁剪，在安卓上不生效

### ISSUE THREAD

**Issue by cze2014** [fairygui/FairyGUI-cocos2dx#40]
尝试使用cocos原生的ClippingNode进行图片裁剪，是不会有问题的。
fgui里面的FUIContainer其实是拿了ClippingNode的代码过来再进行改动封装，对两者进行了比较，可能出问题的地方两者都没区别，但fgui的裁剪确实在安卓版上不生效（IOS还未测试。）。

另外，屏蔽了FUIContainer里面的n->setGLProgram(p); 在安卓版上就能正常出现裁剪效果了，但这样改绝壁是错的=。=！ 找不到问题在哪，所以麻烦大大有空可以看看……

**Comment by xiaoguzhu** [comment]
你看看FUIContainer上面那一堆宏。看看有没有搞对。

**Comment by cze2014** [comment]
#if (CC_TARGET_PLATFORM == CC_PLATFORM_MAC || CC_TARGET_PLATFORM == CC_PLATFORM_WIN32 || CC_TARGET_PLATFORM == CC_PLATFORM_LINUX)
#define CC_CLIPPING_NODE_OPENGLES 0
#else
#define CC_CLIPPING_NODE_OPENGLES 1
#endif

没改过，也和cocos源码对比过，是一样的。 如果宏的条件加上CC_TARGET_PLATFORM ==CC_PLATFORM_ANDROID 那么安卓上裁剪就会生效。 其实效果就和注释了n->setGLProgram(p);一样……

**Comment by xiaoguzhu** [comment]
那不就行了吗，问题在哪？

**Comment by cze2014** [comment]
cocos源码并没有加上CC_PLATFORM_ANDROID的宏啊，看得出源码的目的是当安卓平台时，CC_CLIPPING_NODE_OPENGLES的值为1，然后在ClippingNode里会多执行几段代码。     当前FUIContainer里面的宏定义也是和cocos的一样的。   如果我改成：
#if (CC_TARGET_PLATFORM == CC_PLATFORM_MAC || CC_TARGET_PLATFORM == CC_PLATFORM_WIN32 || CC_TARGET_PLATFORM == CC_PLATFORM_LINUX || CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID)
#define CC_CLIPPING_NODE_OPENGLES 0
#else
#define CC_CLIPPING_NODE_OPENGLES 1
#endif

那么CC_CLIPPING_NODE_OPENGLES的值为0，对应就会少执行几段代码了（我觉得那几段代码cocos是想在其他平台上需要运行的）。 


而且这样加了宏，也改变了cocos源码里面对 CC_CLIPPING_NODE_OPENGLES的宏定义，如果实在没办法，我还是屏蔽了n->setGLProgram(p);（虽然觉得这样改肯定不对……），起码不会影响cocos那边。

**Comment by xiaoguzhu** [comment]
这我就不大清楚了，这一块代码我也不看懂，你也看到，我是复制ClippingNode的。具体要你自己研究了。

**Comment by cze2014** [comment]
那我先把n->setGLProgram(p);屏蔽了，以后有时间再回头看看这问题是怎么回事。
