### ISSUE TITLE
使用bmfont的文本设置上下居中后, 文本向下偏移

### ISSUE THREAD

**Issue by dingmingxin** [fairygui/FairyGUI-cocos2dx#41]
如题。
使用bmfont的的文本设置上下居中后，文本向下偏移。
系统字体没有问题。

FairyguiEditor 版本： 3.10.4(MAC)

**Comment by xiaoguzhu** [comment]
请给出效果截图，设置截图等详细信息。

**Comment by dingmingxin** [comment]
设置：
![image](https://user-images.githubusercontent.com/1784887/55158126-1c68ff00-5199-11e9-9598-9e6a2f30115e.png)

效果
![image](https://user-images.githubusercontent.com/1784887/55158164-31de2900-5199-11e9-8e1d-019bf0de449a.png)

**Comment by dingmingxin** [comment]
如果是设置靠下对齐的话，文字会更靠下

**Comment by dingmingxin** [comment]
请问这里是我设置的有问题还是哪里有问题，有没有解决方案呢？ @xiaoguzhu
