### ISSUE TITLE
按钮变灰后，游戏中按钮上的文本不显示了

### ISSUE THREAD

**Issue by willy8811** [fairygui/FairyGUI-cocos2dx#42]
![image](https://user-images.githubusercontent.com/49179493/55375259-16c73c80-553e-11e9-9832-8ba30719f56b.png)

![image](https://user-images.githubusercontent.com/49179493/55375272-1fb80e00-553e-11e9-8dd5-ae88f34a7978.png)

在编辑器上将按钮变灰，在跑游戏的时候按钮上的icon变灰了，但是按钮上的title看不到了。希望按钮上的title也能和编辑器显示的一样是变灰的 @xiaoguzhu

**Comment by xiaoguzhu** [comment]
待测试
