### ISSUE TITLE
Particle Editor

### ISSUE THREAD

**Issue by imtrobin** [fairygui/FairyGUI-cocos2dx#51]
Hi, I noticed there is no particle editor in fairyeditor. CococsStudio and Creator have particle node.

**Comment by xiaoguzhu** [comment]
yes

**Comment by imtrobin** [comment]
Is there plans to make that happen? Also I used a external tool to generate texture atlas, it does not seem to support importing texture atlas.

**Comment by xiaoguzhu** [comment]
1.Yes
2.You should split it into images first.

**Comment by imtrobin** [comment]
Can I control which images get buillt into an atlas. E.g if I put the images in one folder, then it generate a texture altas from that folder only?

**Comment by xiaoguzhu** [comment]
Double click a image in packages panel or right click a folder and select 'properties' in context menu.
In both dialogs you can change the atlas.

**Comment by imtrobin** [comment]
thanks
