### ISSUE TITLE
整体修改

### ISSUE THREAD

**Issue by ykhangkeong** [fairygui/FairyGUI-cocos2dx#52]
尝试使用控制器把全部组图整体一起添加动画控制颜色和大小。
找不到能把全部的图片组了一起调整深度和一起改变大小。每张图之间的距离都不一样需要保持之间的距离不能更改。水平布局和垂直布局做不到我要的。

![group](https://user-images.githubusercontent.com/406070/58449204-1b266500-813d-11e9-8092-5d78678253ae.jpg)

**Comment by xiaoguzhu** [comment]
把这一堆东西放进一个组件里，那就可以整体调整深度和大小了（你应该指的是scale）。颜色可以对组件使用颜色滤镜。保持距离只需要每个元素都对容器设置左左%就行。

**Comment by ykhangkeong** [comment]
- 我把一堆东西放进一个组件里尝试了几次拿不到我要的效果。看图" group_scale.jpg"
![group_scale](https://user-images.githubusercontent.com/406070/58452409-d81ebe80-8149-11e9-8619-4c1c22c0998d.jpg)

- 在组里没办法加控制颜色动画，我需要在每个元素各自都添加颜色控制吗？ 看图"animate_group.jpg"
![animate_group](https://user-images.githubusercontent.com/406070/58452408-d7862800-8149-11e9-8a0b-f172fb23dc34.jpg)

**Comment by xiaoguzhu** [comment]
不是组，是组件。不是颜色控制，是颜色滤镜。你自己慢慢摸索了。

**Comment by ykhangkeong** [comment]
如果使用组件方法，如何用按钮跟换不同的组件?组件里又有多个元素，元素又能去到其它界面。需要写脚本？
![menu](https://user-images.githubusercontent.com/406070/58458150-048f0680-815b-11e9-92a0-4866234b6c5c.jpg)

**Comment by xiaoguzhu** [comment]
官网教程 还有demo估计没看吧。这种使用问题不适合用github issue继续讨论了。可以入Q群和网友讨论。
