### ISSUE TITLE
富文本框上下居中无效

### ISSUE THREAD

**Issue by sherererlock** [fairygui/FairyGUI-cocos2dx#55]
如题
编辑器中效果图如下
![image](https://user-images.githubusercontent.com/9498229/61027667-575e0e00-a3e9-11e9-9878-a905cc4e2c6f.png)
cocos引擎运行效果如下
![image](https://user-images.githubusercontent.com/9498229/61027705-6e046500-a3e9-11e9-97aa-7ef99305c082.png)

**Comment by xiaoguzhu** [comment]
这个CCRichText应该不支持。

**Comment by sherererlock** [comment]
![image](https://user-images.githubusercontent.com/9498229/61138328-e5291e80-a4f9-11e9-8cd2-93ac4f953edd.png)
这是FUIRichText::formarRenderers()方法的截图，应该在计算delta的地方加上对居中方式的处理就行了吧？
FUIRichText中的文字都是用FUILabel来处理的，没用ccRichText

**Comment by sherererlock** [comment]
> 这个CCRichText应该不支持。

![image](https://user-images.githubusercontent.com/9498229/61138328-e5291e80-a4f9-11e9-8cd2-93ac4f953edd.png)
这是FUIRichText::formarRenderers()方法的截图，应该在计算delta的地方加上对居中方式的处理就行了吧？
FUIRichText中的文字都是用FUILabel来处理的，没用ccRichText

**Comment by xiaoguzhu** [comment]
记错了，和creator混淆了。
