### ISSUE TITLE
Transition 的 playReverse 使用的 Tween 的 Ease 没有相应的 Reverse

### ISSUE THREAD

**Issue by atship** [fairygui/FairyGUI-cocos2dx#86]
Transition.cpp 815 行
```c++
item->tweener->setDelay(time)
       ->setEase(item->tweenConfig->easeType)
```
这里使用的 easeType 和 Reverse 之前是一样的，导致的结果就是动效并不是严格的 Reverse 播放

**Comment by xiaoguzhu** [comment]
没有的，设计如此。

**Comment by atship** [comment]
了解，就是结果有点儿怪异，比如 scale(0->1) back out, reverse 以后变成 scale(1->0) back out，会先缩小到0，然后又返回到0.1左右，最后消失。
