### ISSUE TITLE
cmake GLoader3D 编译出错， cocos2dx4.0

### ISSUE THREAD

**Issue by BrickCar** [fairygui/FairyGUI-cocos2dx#91]
libfairygui/Classes/GLoader3D.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler

**Comment by xiaoguzhu** [comment]
就这一行？

**Comment by xitontong** [comment]
![image](https://user-images.githubusercontent.com/9247156/113696210-477d7600-9704-11eb-90c5-9c12b4ade4b0.png)
cocos 3.17.2版本
xcode 11.1

**Comment by BrickCar** [comment]
集成的spine版本不正确，重新集成就可以了
