### ISSUE TITLE
Black line is shown between images placed side by side

### ISSUE THREAD

**Issue by rizwangaminations** [fairygui/FairyGUI-cocos2dx#95]
Please check
![Screenshot_20210601-134229_Cleopatra Slots](https://user-images.githubusercontent.com/31472835/122938936-9befd380-d38c-11eb-877e-7f0a86da30f3.jpg)

if I set two pngs side by side on FGUI-editor they are shown with a black line between them.
I am new to this, please let me know if you need more information.

**Comment by xiaoguzhu** [comment]
Double click the images in FairyGUI editor, and then check 'Duplicate padding'.

**Comment by rizwangaminations** [comment]
Great thank you, it solved the issue.
