### ISSUE TITLE
GSlider 最小值不为 0 时，滑块位置和 value 不一致。

### ISSUE THREAD

**Issue by HaizhiH** [fairygui/FairyGUI-cocos2dx#96]
如上所述。

由于作者未处理 PR，所以我采用 issue 这种错误的方式提交解决方案以作记录。欢迎讨论。

### 解决方案：
在 GSlider 的 `update()` 函数中，将 `percent` 的计算方式修改如下：
``` C++
float percent = MIN((_value - _min) / (_max - _min), 1);
```

**Comment by xiaoguzhu** [comment]
你的PR在哪里？

**Comment by HaizhiH** [comment]
我的表述有问题，我的意思是看到有很多很久之前的 PR 尚未处理，所以干脆写到 issue 里来。
新的 PR 已经提交，https://github.com/fairygui/FairyGUI-cocos2dx/pull/97
